pipeline {
    agent any // 这表示Pipeline可以在任何可用的Jenkins代理上执行
    stages {
        stage('Build') {
            steps {
                // 使用Python编译模块的步骤
                script {
                    // 假设Python已安装在Jenkins代理上
                    sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                }
            }
        }
    }
}